### ISSUE TITLE
please consider adding a license

### ISSUE THREAD

**Issue by ttyridal** [goncalopp/srtp_decryption#1]
Hi,

I would probably like to use your code, but there is no license applied

**Comment by goncalopp** [comment]
Hi,

I'm happy to licence it under CC-0, BSD, or anything else, really, let me know if it makes any difference for you

IIRC, some functions are still missing. If you happen to write something useful for the general public and are in a position to release it, I'll be happy to integrate your changes

**Comment by ttyridal** [comment]
That's great. No, it doesn't make any difference to me, as long as the terms are clear. Use the one you feel most comfortable with.

I'll post pull requests on any contributions.  I have py3 compatibility just around the corner.

**Comment by goncalopp** [comment]
Nice!
I've licensed this with MIT
